from typing import Dict, List
from backend.models import UniverseMeta, StockQuote, StockFundamentals, ValuationMultiples, Financials, StabilityScore, AnalystTargets

UNIVERSES_META: Dict[str, UniverseMeta] = {
    "global-megacaps": UniverseMeta(
        id="global-megacaps",
        name="Global Megacaps",
        region="Global",
        currency="USD",
        constituentCount=8,
        flag="🌐",
        description="Top trillion-dollar market cap titans and technology innovators.",
    ),
    "sp-500": UniverseMeta(
        id="sp-500",
        name="S&P 500 Leaders",
        region="US",
        currency="USD",
        constituentCount=8,
        flag="🇺🇸",
        description="Leading large-cap equities representing core US industrial economy.",
    ),
    "nasdaq-100": UniverseMeta(
        id="nasdaq-100",
        name="NASDAQ 100 Tech",
        region="US",
        currency="USD",
        constituentCount=8,
        flag="💻",
        description="High-growth software, semiconductor, and internet infrastructure giants.",
    ),
    "nifty-500": UniverseMeta(
        id="nifty-500",
        name="NIFTY 500 (India)",
        region="India",
        currency="INR",
        constituentCount=8,
        flag="🇮🇳",
        description="India's leading diversified conglomerates, banks, and IT services.",
    ),
    "sensex-30": UniverseMeta(
        id="sensex-30",
        name="BSE Sensex 30",
        region="India",
        currency="INR",
        constituentCount=8,
        flag="🇮🇳",
        description="Benchmark index of the Bombay Stock Exchange with top 30 blue-chips.",
    ),
    "ftse-100": UniverseMeta(
        id="ftse-100",
        name="FTSE 100 (UK)",
        region="United Kingdom",
        currency="GBP",
        constituentCount=6,
        flag="🇬🇧",
        description="London Stock Exchange top international corporations and energy giants.",
    ),
    "dax-40": UniverseMeta(
        id="dax-40",
        name="DAX 40 (Germany)",
        region="Germany",
        currency="EUR",
        constituentCount=6,
        flag="🇩🇪",
        description="Frankfurt premier benchmark of German automotive, industrial, and software leaders.",
    ),
}

INITIAL_STOCKS: Dict[str, List[StockQuote]] = {
    "global-megacaps": [
        StockQuote(
            symbol="NVDA",
            name="NVIDIA Corporation",
            exchange="NASDAQ",
            currency="USD",
            price=132.85,
            change=4.65,
            changePercent=3.63,
            open=128.90,
            high=134.10,
            low=128.40,
            previousClose=128.20,
            volume=48920100,
            avgVolume=51200000,
            marketCap=3265000000000,
            marketCapFormatted="$3.27 T",
            peRatio=52.4,
            eps=2.54,
            dividendYield=0.03,
            week52High=140.76,
            week52Low=45.11,
            sparkline=[126.0, 127.5, 127.0, 129.0, 131.0, 130.5, 133.0, 132.85],
            sector="Technology",
            industry="Semiconductors",
            lastUpdated="Live",
        ),
        StockQuote(
            symbol="AAPL",
            name="Apple Inc.",
            exchange="NASDAQ",
            currency="USD",
            price=228.40,
            change=2.60,
            changePercent=1.15,
            open=225.80,
            high=229.10,
            low=225.40,
            previousClose=225.80,
            volume=38210400,
            avgVolume=44000000,
            marketCap=3480000000000,
            marketCapFormatted="$3.48 T",
            peRatio=34.2,
            eps=6.68,
            dividendYield=0.44,
            week52High=237.23,
            week52Low=164.08,
            sparkline=[225.0, 226.0, 225.5, 227.0, 228.0, 227.5, 228.4],
            sector="Technology",
            industry="Consumer Electronics",
            lastUpdated="Live",
        ),
        StockQuote(
            symbol="MSFT",
            name="Microsoft Corporation",
            exchange="NASDAQ",
            currency="USD",
            price=428.15,
            change=-1.85,
            changePercent=-0.43,
            open=430.00,
            high=431.50,
            low=426.80,
            previousClose=430.00,
            volume=19400200,
            avgVolume=21000000,
            marketCap=3180000000000,
            marketCapFormatted="$3.18 T",
            peRatio=36.8,
            eps=11.63,
            dividendYield=0.71,
            week52High=468.35,
            week52Low=309.45,
            sparkline=[430.0, 431.0, 429.5, 428.0, 429.0, 427.5, 428.15],
            sector="Technology",
            industry="Software - Infrastructure",
            lastUpdated="Live",
        ),
        StockQuote(
            symbol="GOOGL",
            name="Alphabet Inc.",
            exchange="NASDAQ",
            currency="USD",
            price=178.60,
            change=3.10,
            changePercent=1.77,
            open=175.50,
            high=179.20,
            low=175.00,
            previousClose=175.50,
            volume=21900400,
            avgVolume=23000000,
            marketCap=2210000000000,
            marketCapFormatted="$2.21 T",
            peRatio=24.6,
            eps=7.26,
            dividendYield=0.45,
            week52High=191.75,
            week52Low=120.21,
            sparkline=[175.0, 176.0, 175.8, 177.0, 178.5, 178.0, 178.6],
            sector="Communication Services",
            industry="Internet Content & Information",
            lastUpdated="Live",
        ),
    ],
}

STOCK_FUNDAMENTALS: Dict[str, StockFundamentals] = {
    "NVDA": StockFundamentals(
        symbol="NVDA",
        name="NVIDIA Corporation",
        sector="Technology",
        industry="Semiconductors",
        country="United States",
        employees=29600,
        ceo="Jensen Huang",
        description="NVIDIA Corporation pioneers GPU-accelerated computing. It specializes in products and platforms for AI, scientific computing, graphics, mobile devices, and automotive applications, dominating AI datacenter infrastructure.",
        valuation=ValuationMultiples(
            peRatio=52.4,
            forwardPe=29.8,
            pegRatio=1.15,
            priceToBook=48.2,
            evToEbitda=38.4,
            marketCapFormatted="$3.27 T",
            enterpriseValueFormatted="$3.24 T",
        ),
        financials=Financials(
            revenueFormatted="$96.3 B",
            revenueGrowthYoy=122.4,
            grossMargin=75.1,
            operatingMargin=62.3,
            netMargin=53.4,
            roe=91.5,
            roa=48.2,
            debtToEquity=0.18,
            currentRatio=3.5,
            freeCashFlowFormatted="$39.2 B",
        ),
        stabilityScore=StabilityScore(
            total=94,
            profitability=25,
            balanceSheet=24,
            growth=25,
            momentum=20,
            rating="Prime",
        ),
        analysts=AnalystTargets(
            consensus="Strong Buy",
            targetMean=151.20,
            targetHigh=200.00,
            targetLow=90.00,
            analystCount=60,
            upsidePercent=13.8,
        ),
        keyRisks=[
            "Concentrated revenue among top hyperscaler cloud providers",
            "Geopolitical trade restrictions on high-end accelerator exports",
        ],
        catalysts=[
            "Blackwell architecture volume ramp and pricing power",
            "Sovereign AI initiatives expanding demand beyond commercial cloud",
        ],
    ),
}
